import type { CurriculumLesson, QuizQuestion } from "@/lib/data/types";

function question(
  id: string,
  prompt: string,
  choices: [string, string, string],
  correctIndex: 0 | 1 | 2,
  explanation: string,
): QuizQuestion {
  const choiceIds = ["a", "b", "c"];
  return {
    id,
    prompt,
    choices: choices.map((label, index) => ({ id: choiceIds[index], label })),
    correctChoiceId: choiceIds[correctIndex],
    explanation,
  };
}

/**
 * Version-controlled curriculum is reviewed content. Student attempts live in
 * Supabase. Adding an Academy lesson should normally require editing only this
 * collection, not the lesson player.
 */
export const CURRICULUM_LESSONS: readonly CurriculumLesson[] = [
  {
    id: "l1-home-row-letters",
    slug: "home-row-landmarks",
    academy: "keyboard",
    broadTrack: "keyboard",
    specificTopic: "home row",
    unitId: "keyboard-foundations",
    title: "Home Row Landmarks",
    gradeBand: "3-5",
    curriculumLevel: "foundation",
    typingLevel: "beginner",
    typingObjective: "Find A, S, D, F, J, K, L, and semicolon by touch.",
    targetedTypingSkills: ["home-row placement", "F and J landmarks", "correct fingers"],
    learningOutcome: "Use the F and J landmarks to place both hands on home row without looking down.",
    miniLesson:
      "The home row is your keyboard home base. Rest your left fingers on A, S, D, F and your right fingers on J, K, L, semicolon. The bumps on F and J help you return without looking down.",
    typingPassage: "asdf jkl; asdf jkl; ffjj ddkk slsl a;a; fjfj dkdk",
    thinkPrompt: "How can the bumps on F and J help you type without looking down?",
    thinkMinLength: 15,
    thinkMaxLength: 240,
    quizBank: [
      question("home-1", "Which keys have raised bumps?", ["A and semicolon", "F and J", "D and K"], 1, "F and J are tactile landmarks for both index fingers."),
      question("home-2", "Where do your fingers return after a reach?", ["The home row", "The number row", "The spacebar"], 0, "The home row is the resting position for touch typing."),
      question("home-3", "Which finger rests on F?", ["Left index finger", "Right index finger", "Left pinky"], 0, "Your left index finger rests on F."),
      question("home-4", "Why avoid looking down?", ["It makes the keys quieter", "It builds touch memory", "It changes the font"], 1, "Returning by feel builds reliable muscle memory."),
      question("home-5", "Your hands lose their place. What should you do first?", ["Find the F and J bumps", "Press random keys", "Move to the number row"], 0, "The F and J bumps help both hands return to home row."),
    ],
    vocabulary: [
      { term: "home row", definition: "The middle keyboard row where your fingers rest." },
      { term: "landmark", definition: "A feature that helps you find a position." },
    ],
    tags: ["home-row", "finger-placement", "accuracy"],
    estimatedTime: 5,
    xpValue: 40,
    mastery: { targetAccuracy: 90, targetQuizPercentage: 67, minimumSuccessfulAttempts: 1 },
    isCore: true,
    sequence: 1,
    status: "published",
    locale: "en-US",
    level: 1,
    order: 1,
    focus: "Find the home row by feel: a s d f j k l ;",
    category: "letters",
    promptType: "english",
    track: "basics",
    sampleText: "asdf jkl; asdf jkl; ffjj ddkk slsl a;a; fjfj dkdk",
    estimatedMinutes: 5,
  },
  {
    id: "l2-home-row-words",
    slug: "steady-home-row-words",
    academy: "keyboard",
    broadTrack: "keyboard",
    specificTopic: "accuracy",
    unitId: "keyboard-foundations",
    title: "Steady Home Row Words",
    gradeBand: "3-5",
    curriculumLevel: "foundation",
    typingLevel: "beginner",
    typingObjective: "Type short home-row words with a steady rhythm.",
    targetedTypingSkills: ["home-row words", "steady rhythm", "accuracy control"],
    learningOutcome: "Type short home-row words at a controlled pace and choose an accuracy-first response to mistakes.",
    miniLesson:
      "Accuracy comes before speed. Type each word at a pace you can control, use the correct finger, and let your hands return to home row. A smooth rhythm is more useful than a rushed burst.",
    typingPassage: "as ask sad lad fall flask salad all dads",
    thinkPrompt: "Describe one way you can choose accuracy over speed while practicing.",
    thinkMinLength: 15,
    thinkMaxLength: 240,
    quizBank: [
      question("steady-1", "What should come before speed?", ["Accuracy", "Volume", "Guessing"], 0, "Accurate repetitions build dependable technique."),
      question("steady-2", "What does a steady rhythm mean?", ["Random bursts", "A controlled pace", "Holding every key"], 1, "A controlled pace helps you stay accurate."),
      question("steady-3", "After reaching for a key, where should your finger return?", ["Your lap", "The number row", "Home row"], 2, "Home row keeps your hands oriented."),
      question("steady-4", "What is the best response to repeated mistakes?", ["Slow down slightly", "Type harder", "Skip the word"], 0, "Slowing down gives your fingers time to use the correct motion."),
      question("steady-5", "You are fast but missing many letters. What is the useful next step?", ["Speed up", "Slow to a controllable rhythm", "Stop using home row"], 1, "A controllable rhythm lets accurate motions become repeatable."),
    ],
    vocabulary: [{ term: "rhythm", definition: "A regular, controlled pattern of movement." }],
    tags: ["home-row", "words", "accuracy"],
    estimatedTime: 5,
    xpValue: 40,
    mastery: { targetAccuracy: 90, targetQuizPercentage: 67, minimumSuccessfulAttempts: 1 },
    prerequisiteLessonIds: ["l1-home-row-letters"],
    isCore: true,
    sequence: 2,
    status: "published",
    locale: "en-US",
    level: 2,
    order: 2,
    focus: "Build real words using only the home row keys.",
    category: "words",
    promptType: "english",
    track: "basics",
    sampleText: "as ask sad lad fall flask salad all dads",
    estimatedMinutes: 5,
  },
  {
    id: "l3-top-bottom-rows",
    slug: "reach-and-return",
    academy: "keyboard",
    broadTrack: "keyboard",
    specificTopic: "keyboard geography",
    unitId: "keyboard-alphabet",
    title: "Reach and Return",
    gradeBand: "3-5",
    curriculumLevel: "foundation",
    typingLevel: "full-alphabet",
    typingObjective: "Reach to the top and bottom rows, then return to home row.",
    targetedTypingSkills: ["full alphabet", "top-row reach", "bottom-row reach", "home-row return"],
    learningOutcome: "Reach for top- and bottom-row letters with the assigned finger and return to home row.",
    miniLesson:
      "Each finger owns a small column of keys. Reach from home row instead of moving your whole hand. After every reach, return to your home-row landmark so the next key is easier to find.",
    typingPassage: "the quick red fox can type now while very busy cats move",
    thinkPrompt: "Why is returning to home row useful after reaching for another key?",
    thinkMinLength: 15,
    thinkMaxLength: 240,
    quizBank: [
      question("reach-1", "What should move during a short reach?", ["One finger", "Your whole chair", "Both hands"], 0, "A small finger reach keeps the rest of your hand oriented."),
      question("reach-2", "What happens after a reach?", ["Keep the finger away", "Return to home row", "Look at the keyboard"], 1, "Returning resets your position."),
      question("reach-3", "Why do fingers have key columns?", ["To organize efficient movement", "To color the keyboard", "To change the screen"], 0, "Finger zones reduce unnecessary hand movement."),
      question("reach-4", "Which goal matters most during a new reach?", ["Maximum speed", "Correct finger control", "Loud key presses"], 1, "Controlled, correct motions build speed later."),
      question("reach-5", "After typing a top-row letter, your hand drifts upward. What should you change?", ["Return the reaching finger to home row", "Move both hands upward", "Look down after every key"], 0, "Returning the reaching finger keeps the hand oriented for the next letter."),
    ],
    vocabulary: [{ term: "key column", definition: "A group of keys assigned to one finger." }],
    tags: ["rows", "reach", "finger-placement"],
    estimatedTime: 5,
    xpValue: 45,
    mastery: { targetAccuracy: 90, targetQuizPercentage: 67, minimumSuccessfulAttempts: 1 },
    prerequisiteLessonIds: ["l2-home-row-words"],
    isCore: true,
    sequence: 7,
    status: "published",
    locale: "en-US",
    level: 3,
    order: 3,
    focus: "Reach up and down without looking at your hands.",
    category: "rows",
    promptType: "english",
    track: "basics",
    sampleText: "the quick red fox can type now while very busy cats move",
    estimatedMinutes: 5,
  },
  {
    id: "academy-chromebook-tabs",
    slug: "tabs-with-a-purpose",
    academy: "chromebook",
    broadTrack: "chromebook",
    specificTopic: "browser tabs",
    unitId: "chromebook-navigation",
    title: "Tabs With a Purpose",
    gradeBand: "3-5",
    curriculumLevel: "foundation",
    typingLevel: "punctuation",
    typingObjective: "Type complete sentences with capitalization and punctuation.",
    targetedTypingSkills: ["capitalization", "commas", "periods", "sentence spacing"],
    learningOutcome: "Explain and apply one rule for keeping browser tabs purposeful and organized.",
    miniLesson:
      "A browser tab holds one webpage. Keep only the tabs you need, read each tab title before switching, and close finished work. Fewer purposeful tabs make schoolwork easier to find.",
    typingPassage: "A browser tab holds one page. Keep useful tabs open, and close a tab when the task is finished.",
    thinkPrompt: "What is one rule you could use to keep your school tabs organized?",
    thinkMinLength: 20,
    thinkMaxLength: 280,
    quizBank: [
      question("tabs-1", "What does one browser tab hold?", ["One webpage", "Every file", "The keyboard settings"], 0, "Each tab displays one webpage at a time."),
      question("tabs-2", "When should you close a tab?", ["Before reading it", "When its task is finished", "Never"], 1, "Closing finished work reduces clutter."),
      question("tabs-3", "What helps you choose the correct tab?", ["Its title", "Its volume", "Its battery level"], 0, "The tab title identifies its page."),
      question("tabs-4", "Why keep fewer tabs open?", ["To make the keys larger", "To find work more easily", "To erase browsing history"], 1, "A focused tab set makes current work easier to locate."),
      question("tabs-5", "You finish an article but still have six tabs open. What is the best action?", ["Close the finished article tab", "Open a duplicate", "Rename every file"], 0, "Closing a finished tab reduces clutter while keeping active work available."),
    ],
    vocabulary: [{ term: "browser tab", definition: "A labeled section of a browser that displays a webpage." }],
    tags: ["chromebook", "tabs", "organization"],
    estimatedTime: 5,
    xpValue: 50,
    mastery: { targetAccuracy: 92, targetQuizPercentage: 67, minimumSuccessfulAttempts: 1 },
    isCore: true,
    sequence: 1,
    status: "published",
    locale: "en-US",
    relatedPracticeHref: "/shortcuts",
    level: 4,
    order: 14,
    focus: "Use and organize browser tabs on a school device.",
    category: "sentences",
    promptType: "english",
    track: "basics",
    sampleText: "A browser tab holds one page. Keep useful tabs open, and close a tab when the task is finished.",
    estimatedMinutes: 5,
  },
  {
    id: "academy-digital-passwords",
    slug: "strong-memorable-passwords",
    academy: "digital",
    broadTrack: "digital",
    specificTopic: "password safety",
    unitId: "digital-security",
    title: "Strong, Memorable Passwords",
    gradeBand: "6-8",
    curriculumLevel: "foundation",
    typingLevel: "intermediate",
    typingObjective: "Practice complete sentences with capitals, spaces, and periods accurately.",
    targetedTypingSkills: ["capitalization", "sentence spacing", "periods"],
    learningOutcome: "Identify password habits that make account compromise less likely to spread.",
    miniLesson:
      "A strong password is long, unique, and hard for someone else to guess. A passphrase combines several unrelated words. Never reuse a school password or share it with friends.",
    typingPassage: "A long passphrase can be memorable and hard to guess. Use a unique password for every important account.",
    thinkPrompt: "Without sharing a real password, name one change that can make a password harder to guess.",
    thinkMinLength: 20,
    thinkMaxLength: 280,
    quizBank: [
      question("password-1", "Which password trait is safest?", ["Short", "Unique", "Shared"], 1, "A unique password limits the damage if another account is exposed."),
      question("password-2", "What is a passphrase?", ["Several words combined", "Your first name", "A public hint"], 0, "Several unrelated words can create length while remaining memorable."),
      question("password-3", "Who should receive your school password?", ["A classmate", "A game chat", "No one you do not explicitly trust or authorize"], 2, "Passwords are private credentials and should not be casually shared."),
      question("password-4", "Why avoid reusing passwords?", ["One leak could expose more accounts", "It slows the keyboard", "It changes your username"], 0, "Unique passwords keep one compromised account from unlocking others."),
      question("password-5", "A friend asks for your school password to submit work. What should you do?", ["Share it once", "Keep it private and use an approved help route", "Post it in class chat"], 1, "Credentials should stay private; use a teacher or approved recovery process for help."),
    ],
    vocabulary: [
      { term: "passphrase", definition: "A password made from a sequence of words." },
      { term: "unique", definition: "Used for only one account." },
    ],
    tags: ["passwords", "privacy", "digital-citizenship"],
    estimatedTime: 6,
    xpValue: 55,
    mastery: { targetAccuracy: 91, targetQuizPercentage: 67, minimumSuccessfulAttempts: 1 },
    isCore: true,
    sequence: 1,
    status: "published",
    locale: "en-US",
    level: 5,
    order: 15,
    focus: "Learn what makes account credentials safer.",
    category: "sentences",
    promptType: "english",
    track: "basics",
    sampleText: "A long passphrase can be memorable and hard to guess. Use a unique password for every important account.",
    estimatedMinutes: 6,
  },
  {
    id: "academy-communication-tone",
    slug: "respectful-help-message",
    academy: "communication",
    broadTrack: "communication",
    specificTopic: "tone and audience",
    unitId: "communication-messages",
    title: "Ask for Help Clearly",
    gradeBand: "6-8",
    curriculumLevel: "developing",
    typingLevel: "punctuation",
    typingObjective: "Type a polished message with capitals, commas, and question marks.",
    targetedTypingSkills: ["capitalization", "commas", "question marks", "message punctuation"],
    learningOutcome: "Construct a respectful help request that states what was tried, names the problem, and asks a clear question.",
    miniLesson:
      "A useful help message says what you tried, names the problem, and asks one clear question. Respectful tone is direct without blaming the reader. Reread before sending.",
    typingPassage: "Hello Ms. Lee, I reviewed the example, but I am still stuck on step three. Could you help me find my mistake?",
    thinkPrompt: "Rewrite “This makes no sense. Fix it.” as a respectful request for help.",
    thinkMinLength: 25,
    thinkMaxLength: 320,
    quizBank: [
      question("tone-1", "What should a help message explain?", ["What you already tried", "A classmate's password", "Nothing specific"], 0, "Sharing what you tried helps the reader give focused support."),
      question("tone-2", "Which tone is most useful?", ["Blaming", "Clear and respectful", "Vague"], 1, "A clear, respectful request makes cooperation easier."),
      question("tone-3", "What should you do before sending?", ["Add random capitals", "Reread the message", "Remove the question"], 1, "Rereading catches unclear or harsh wording."),
      question("tone-4", "Which question is clearest?", ["Help?", "Why is everything wrong?", "Could you explain step three?"], 2, "A specific question tells the reader exactly where help is needed."),
      question("tone-5", "A teacher cannot tell where you are stuck. What detail should you add?", ["The step you tried", "More blame", "An unrelated joke"], 0, "Naming the attempted step gives the reader useful context."),
    ],
    vocabulary: [
      { term: "tone", definition: "The attitude communicated by your word choices." },
      { term: "audience", definition: "The person or group receiving a message." },
    ],
    tags: ["email", "tone", "asking-for-help"],
    estimatedTime: 6,
    xpValue: 55,
    mastery: { targetAccuracy: 92, targetQuizPercentage: 67, minimumSuccessfulAttempts: 1 },
    isCore: true,
    sequence: 6,
    status: "published",
    locale: "en-US",
    level: 6,
    order: 16,
    focus: "Ask for help with clarity and respect.",
    category: "punctuation",
    promptType: "english",
    track: "basics",
    sampleText: "Hello Ms. Lee, I reviewed the example, but I am still stuck on step three. Could you help me find my mistake?",
    estimatedMinutes: 6,
  },
  {
    id: "academy-money-saving-half",
    slug: "save-half",
    academy: "money",
    broadTrack: "money",
    specificTopic: "saving",
    unitId: "money-saving",
    title: "Save Half First",
    gradeBand: "3-5",
    curriculumLevel: "foundation",
    typingLevel: "numbers-symbols",
    typingObjective: "Type numbers, dollar amounts, and complete sentences accurately.",
    targetedTypingSkills: ["number row", "dollar sign", "capitalization", "periods"],
    learningOutcome: "Calculate half of a simple amount and explain why planned savings should be set aside before optional spending.",
    miniLesson:
      "Saving means keeping some money for later instead of spending it now. If you decide to save half, divide the total into two equal parts before you buy anything.",
    typingPassage: "If I earn $20 and save half, I put $10 aside. The other $10 is available for spending or another goal.",
    thinkPrompt: "If you earned $20 and wanted to save half, how much would you save? Explain your thinking.",
    thinkMinLength: 15,
    thinkMaxLength: 240,
    quizBank: [
      question("save-1", "What is half of $20?", ["$5", "$10", "$15"], 1, "Two equal groups of $10 make $20."),
      question("save-2", "What does saving mean?", ["Keeping money for later", "Spending everything now", "Losing a receipt"], 0, "Saved money is set aside for a later need or goal."),
      question("save-3", "When should you set aside planned savings?", ["Before optional spending", "Only after spending", "Never"], 0, "Saving first protects the amount you planned to keep."),
      question("save-4", "If $12 is split in half, what is each part?", ["$4", "$6", "$8"], 1, "Six plus six equals twelve."),
      question("save-5", "You plan to save half of $8. What should you set aside first?", ["$2", "$4", "$8"], 1, "Half of eight is four, so setting aside $4 protects the saving goal."),
    ],
    vocabulary: [
      { term: "save", definition: "To keep money for a future use." },
      { term: "half", definition: "One of two equal parts." },
    ],
    tags: ["saving", "money", "numbers"],
    estimatedTime: 5,
    xpValue: 50,
    mastery: { targetAccuracy: 92, targetQuizPercentage: 67, minimumSuccessfulAttempts: 1 },
    isCore: true,
    sequence: 6,
    status: "published",
    locale: "en-US",
    level: 7,
    order: 17,
    focus: "Practice a simple saving decision.",
    category: "numbers",
    promptType: "english",
    track: "basics",
    sampleText: "If I earn $20 and save half, I put $10 aside. The other $10 is available for spending or another goal.",
    estimatedMinutes: 5,
  },
  {
    id: "academy-life-first-step",
    slug: "find-the-first-step",
    academy: "life",
    broadTrack: "life",
    specificTopic: "task breakdown",
    unitId: "life-starting",
    title: "Find the First Step",
    gradeBand: "6-8",
    curriculumLevel: "developing",
    typingLevel: "intermediate",
    typingObjective: "Type varied sentences with clear punctuation and rhythm.",
    targetedTypingSkills: ["capitalization", "sentence spacing", "periods"],
    learningOutcome: "Turn a vague task into one visible, immediately doable first action.",
    miniLesson:
      "A large task feels smaller when you name one visible first action. “Do my project” is vague; “open the directions and highlight the due date” is specific. Start with an action you can do now.",
    typingPassage: "A clear first step turns a big task into something I can begin. I can open the directions and mark the due date.",
    thinkPrompt: "Choose one task you need to do and write a specific first action for it.",
    thinkMinLength: 20,
    thinkMaxLength: 280,
    quizBank: [
      question("step-1", "What makes a useful first step?", ["It is specific and doable", "It describes the whole month", "It depends on guessing"], 0, "A specific action gives you a clear place to begin."),
      question("step-2", "Which is a first action?", ["Finish everything", "Open the directions", "Be more organized"], 1, "Opening the directions is visible and immediately doable."),
      question("step-3", "Why break down a large task?", ["To make starting easier", "To add more homework", "To hide the deadline"], 0, "Smaller actions reduce uncertainty and help you begin."),
      question("step-4", "Which phrase is too vague?", ["Write the heading", "Set a ten-minute timer", "Do my project"], 2, "“Do my project” does not identify the first physical action."),
      question("step-5", "You need to study for a test. Which first step is most useful?", ["Study everything", "Open the review guide and mark the first topic", "Worry about the score"], 1, "Opening the guide and marking a topic is a visible action you can do now."),
    ],
    vocabulary: [{ term: "action", definition: "A specific thing you can do." }],
    tags: ["planning", "task-breakdown", "executive-function"],
    estimatedTime: 5,
    xpValue: 50,
    mastery: { targetAccuracy: 91, targetQuizPercentage: 67, minimumSuccessfulAttempts: 1 },
    isCore: true,
    sequence: 1,
    status: "published",
    locale: "en-US",
    level: 8,
    order: 18,
    focus: "Turn a vague task into a clear first action.",
    category: "sentences",
    promptType: "english",
    track: "basics",
    sampleText: "A clear first step turns a big task into something I can begin. I can open the directions and mark the due date.",
    estimatedMinutes: 5,
  },
] as const;
